[package]
name = "binbreak"
version = "0.0.1"
description = "A terminal based binary number guessing game"
authors = ["William Raendchen <william@holonaut.io>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
rand = "0.9.1"
